2005-11-26  Hollis Blanchard  <hollis@penguinppc.org>
	* configure.ac: Correct `AC_PROG_YACC' test.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2386,6 +2386,50 @@ fi
 done
 test -n "$YACC" || YACC="yacc"
 
+# AC_PROG_YACC doesn't actually check if yacc exists!
+tmp_yacc=$YACC
+unset YACC
+# Extract the first word of ""$tmp_yacc"", so it can be a program name with args.
+set dummy "$tmp_yacc"; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_YACC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$YACC"; then
+  ac_cv_prog_YACC="$YACC" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_YACC=""$tmp_yacc""
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+YACC=$ac_cv_prog_YACC
+if test -n "$YACC"; then
+  echo "$as_me:$LINENO: result: $YACC" >&5
+echo "${ECHO_T}$YACC" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test "x$YACC" = x; then
+  { { echo "$as_me:$LINENO: error: Could not find $tmp_yacc." >&5
+echo "$as_me: error: Could not find $tmp_yacc." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 
 # Check whether --enable-largefile or --disable-largefile was given.
 if test "${enable_largefile+set}" = set; then
