2004-04-04  Yoshinori K. Okuji  <okuji@enbug.org>
	All symbols prefixed with PUPA_ and pupa_ are renamed to GRUB_
	and grub_, respectively. Because the conversion is trivial and
	mechanical, I omit the details here. Please refer to the CVS
	if you need more information.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_VERSION='1.90'
 PACKAGE_STRING='GRUB 1.90'
 PACKAGE_BUGREPORT='bug-grub@gnu.org'
 
-ac_unique_file="include/pupa/dl.h"
+ac_unique_file="include/grub/dl.h"
 # Factoring default headers for most tests.
 ac_includes_default="\
 #include <stdio.h>
@@ -2693,7 +2693,7 @@ fi
 
 echo "$as_me:$LINENO: checking if C symbols get an underscore after compilation" >&5
 echo $ECHO_N "checking if C symbols get an underscore after compilation... $ECHO_C" >&6
-if test "${pupa_cv_asm_uscore+set}" = set; then
+if test "${grub_cv_asm_uscore+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat > conftest.c <<\EOF
@@ -2719,31 +2719,31 @@ echo "$as_me: error: ${CC-cc} failed to produce assembly code" >&2;}
 fi
 
 if grep _func conftest.s >/dev/null 2>&1; then
-  pupa_cv_asm_uscore=yes
+  grub_cv_asm_uscore=yes
 else
-  pupa_cv_asm_uscore=no
+  grub_cv_asm_uscore=no
 fi
 
 rm -f conftest*
 fi
 
 
-if test "x$pupa_cv_asm_uscore" = xyes; then
+if test "x$grub_cv_asm_uscore" = xyes; then
 
 cat >>confdefs.h <<_ACEOF
-#define HAVE_ASM_USCORE $pupa_cv_asm_uscore
+#define HAVE_ASM_USCORE $grub_cv_asm_uscore
 _ACEOF
 
 fi
 
-echo "$as_me:$LINENO: result: $pupa_cv_asm_uscore" >&5
-echo "${ECHO_T}$pupa_cv_asm_uscore" >&6
+echo "$as_me:$LINENO: result: $grub_cv_asm_uscore" >&5
+echo "${ECHO_T}$grub_cv_asm_uscore" >&6
 
 if test "x$host_cpu" = xi386; then
 
 echo "$as_me:$LINENO: checking if start is defined by the compiler" >&5
 echo $ECHO_N "checking if start is defined by the compiler... $ECHO_C" >&6
-if test "${pupa_cv_check_start_symbol+set}" = set; then
+if test "${grub_cv_check_start_symbol+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -2774,23 +2774,23 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  pupa_cv_check_start_symbol=yes
+  grub_cv_check_start_symbol=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-pupa_cv_check_start_symbol=no
+grub_cv_check_start_symbol=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
 
 
-echo "$as_me:$LINENO: result: $pupa_cv_check_start_symbol" >&5
-echo "${ECHO_T}$pupa_cv_check_start_symbol" >&6
+echo "$as_me:$LINENO: result: $grub_cv_check_start_symbol" >&5
+echo "${ECHO_T}$grub_cv_check_start_symbol" >&6
 
 echo "$as_me:$LINENO: checking if _start is defined by the compiler" >&5
 echo $ECHO_N "checking if _start is defined by the compiler... $ECHO_C" >&6
-if test "${pupa_cv_check_uscore_start_symbol+set}" = set; then
+if test "${grub_cv_check_uscore_start_symbol+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -2821,29 +2821,29 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  pupa_cv_check_uscore_start_symbol=yes
+  grub_cv_check_uscore_start_symbol=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-pupa_cv_check_uscore_start_symbol=no
+grub_cv_check_uscore_start_symbol=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
 
 
-echo "$as_me:$LINENO: result: $pupa_cv_check_uscore_start_symbol" >&5
-echo "${ECHO_T}$pupa_cv_check_uscore_start_symbol" >&6
+echo "$as_me:$LINENO: result: $grub_cv_check_uscore_start_symbol" >&5
+echo "${ECHO_T}$grub_cv_check_uscore_start_symbol" >&6
 
 
 
 
-if test "x$pupa_cv_check_start_symbol" = xyes; then
+if test "x$grub_cv_check_start_symbol" = xyes; then
   cat >>confdefs.h <<\_ACEOF
 #define START_SYMBOL start
 _ACEOF
 
-elif test "x$pupa_cv_check_uscore_start_symbol" = xyes; then
+elif test "x$grub_cv_check_uscore_start_symbol" = xyes; then
   cat >>confdefs.h <<\_ACEOF
 #define START_SYMBOL _start
 _ACEOF
@@ -2857,7 +2857,7 @@ fi
 
 echo "$as_me:$LINENO: checking if __bss_start is defined by the compiler" >&5
 echo $ECHO_N "checking if __bss_start is defined by the compiler... $ECHO_C" >&6
-if test "${pupa_cv_check_uscore_uscore_bss_start_symbol+set}" = set; then
+if test "${grub_cv_check_uscore_uscore_bss_start_symbol+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -2888,23 +2888,23 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  pupa_cv_check_uscore_uscore_bss_start_symbol=yes
+  grub_cv_check_uscore_uscore_bss_start_symbol=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-pupa_cv_check_uscore_uscore_bss_start_symbol=no
+grub_cv_check_uscore_uscore_bss_start_symbol=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
 
 
-echo "$as_me:$LINENO: result: $pupa_cv_check_uscore_uscore_bss_start_symbol" >&5
-echo "${ECHO_T}$pupa_cv_check_uscore_uscore_bss_start_symbol" >&6
+echo "$as_me:$LINENO: result: $grub_cv_check_uscore_uscore_bss_start_symbol" >&5
+echo "${ECHO_T}$grub_cv_check_uscore_uscore_bss_start_symbol" >&6
 
 echo "$as_me:$LINENO: checking if edata is defined by the compiler" >&5
 echo $ECHO_N "checking if edata is defined by the compiler... $ECHO_C" >&6
-if test "${pupa_cv_check_edata_symbol+set}" = set; then
+if test "${grub_cv_check_edata_symbol+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -2935,23 +2935,23 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  pupa_cv_check_edata_symbol=yes
+  grub_cv_check_edata_symbol=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-pupa_cv_check_edata_symbol=no
+grub_cv_check_edata_symbol=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
 
 
-echo "$as_me:$LINENO: result: $pupa_cv_check_edata_symbol" >&5
-echo "${ECHO_T}$pupa_cv_check_edata_symbol" >&6
+echo "$as_me:$LINENO: result: $grub_cv_check_edata_symbol" >&5
+echo "${ECHO_T}$grub_cv_check_edata_symbol" >&6
 
 echo "$as_me:$LINENO: checking if _edata is defined by the compiler" >&5
 echo $ECHO_N "checking if _edata is defined by the compiler... $ECHO_C" >&6
-if test "${pupa_cv_check_uscore_edata_symbol+set}" = set; then
+if test "${grub_cv_check_uscore_edata_symbol+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -2982,34 +2982,34 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  pupa_cv_check_uscore_edata_symbol=yes
+  grub_cv_check_uscore_edata_symbol=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-pupa_cv_check_uscore_edata_symbol=no
+grub_cv_check_uscore_edata_symbol=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
 
 
-echo "$as_me:$LINENO: result: $pupa_cv_check_uscore_edata_symbol" >&5
-echo "${ECHO_T}$pupa_cv_check_uscore_edata_symbol" >&6
+echo "$as_me:$LINENO: result: $grub_cv_check_uscore_edata_symbol" >&5
+echo "${ECHO_T}$grub_cv_check_uscore_edata_symbol" >&6
 
 
 
 
-if test "x$pupa_cv_check_uscore_uscore_bss_start_symbol" = xyes; then
+if test "x$grub_cv_check_uscore_uscore_bss_start_symbol" = xyes; then
   cat >>confdefs.h <<\_ACEOF
 #define BSS_START_SYMBOL __bss_start
 _ACEOF
 
-elif test "x$pupa_cv_check_edata_symbol" = xyes; then
+elif test "x$grub_cv_check_edata_symbol" = xyes; then
   cat >>confdefs.h <<\_ACEOF
 #define BSS_START_SYMBOL edata
 _ACEOF
 
-elif test "x$pupa_cv_check_uscore_edata_symbol" = xyes; then
+elif test "x$grub_cv_check_uscore_edata_symbol" = xyes; then
   cat >>confdefs.h <<\_ACEOF
 #define BSS_START_SYMBOL _edata
 _ACEOF
@@ -3023,7 +3023,7 @@ fi
 
 echo "$as_me:$LINENO: checking if end is defined by the compiler" >&5
 echo $ECHO_N "checking if end is defined by the compiler... $ECHO_C" >&6
-if test "${pupa_cv_check_end_symbol+set}" = set; then
+if test "${grub_cv_check_end_symbol+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -3054,23 +3054,23 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  pupa_cv_check_end_symbol=yes
+  grub_cv_check_end_symbol=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-pupa_cv_check_end_symbol=no
+grub_cv_check_end_symbol=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
 
 
-echo "$as_me:$LINENO: result: $pupa_cv_check_end_symbol" >&5
-echo "${ECHO_T}$pupa_cv_check_end_symbol" >&6
+echo "$as_me:$LINENO: result: $grub_cv_check_end_symbol" >&5
+echo "${ECHO_T}$grub_cv_check_end_symbol" >&6
 
 echo "$as_me:$LINENO: checking if _end is defined by the compiler" >&5
 echo $ECHO_N "checking if _end is defined by the compiler... $ECHO_C" >&6
-if test "${pupa_cv_check_uscore_end_symbol+set}" = set; then
+if test "${grub_cv_check_uscore_end_symbol+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -3101,29 +3101,29 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  pupa_cv_check_uscore_end_symbol=yes
+  grub_cv_check_uscore_end_symbol=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-pupa_cv_check_uscore_end_symbol=no
+grub_cv_check_uscore_end_symbol=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
 
 
-echo "$as_me:$LINENO: result: $pupa_cv_check_uscore_end_symbol" >&5
-echo "${ECHO_T}$pupa_cv_check_uscore_end_symbol" >&6
+echo "$as_me:$LINENO: result: $grub_cv_check_uscore_end_symbol" >&5
+echo "${ECHO_T}$grub_cv_check_uscore_end_symbol" >&6
 
 
 
 
-if test "x$pupa_cv_check_end_symbol" = xyes; then
+if test "x$grub_cv_check_end_symbol" = xyes; then
   cat >>confdefs.h <<\_ACEOF
 #define END_SYMBOL end
 _ACEOF
 
-elif test "x$pupa_cv_check_uscore_end_symbol" = xyes; then
+elif test "x$grub_cv_check_uscore_end_symbol" = xyes; then
   cat >>confdefs.h <<\_ACEOF
 #define END_SYMBOL _end
 _ACEOF
@@ -3140,7 +3140,7 @@ if test "x$host_cpu" = xi386; then
 
 echo "$as_me:$LINENO: checking whether addr32 must be in the same line as the instruction" >&5
 echo $ECHO_N "checking whether addr32 must be in the same line as the instruction... $ECHO_C" >&6
-if test "${pupa_cv_i386_asm_prefix_requirement+set}" = set; then
+if test "${grub_cv_i386_asm_prefix_requirement+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat > conftest.s <<\EOF
@@ -3154,41 +3154,41 @@ if { ac_try='${CC-cc} ${CFLAGS} -c conftest.s'
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; } && test -s conftest.o; then
-  pupa_cv_i386_asm_prefix_requirement=yes
+  grub_cv_i386_asm_prefix_requirement=yes
 else
-  pupa_cv_i386_asm_prefix_requirement=no
+  grub_cv_i386_asm_prefix_requirement=no
 fi
 
 rm -f conftest*
 fi
 
 
-if test "x$pupa_cv_i386_asm_prefix_requirement" = xyes; then
-  pupa_tmp_addr32="addr32"
-  pupa_tmp_data32="data32"
+if test "x$grub_cv_i386_asm_prefix_requirement" = xyes; then
+  grub_tmp_addr32="addr32"
+  grub_tmp_data32="data32"
 else
-  pupa_tmp_addr32="addr32;"
-  pupa_tmp_data32="data32;"
+  grub_tmp_addr32="addr32;"
+  grub_tmp_data32="data32;"
 fi
 
 
 cat >>confdefs.h <<_ACEOF
-#define ADDR32 $pupa_tmp_addr32
+#define ADDR32 $grub_tmp_addr32
 _ACEOF
 
 
 cat >>confdefs.h <<_ACEOF
-#define DATA32 $pupa_tmp_data32
+#define DATA32 $grub_tmp_data32
 _ACEOF
 
 
-echo "$as_me:$LINENO: result: $pupa_cv_i386_asm_prefix_requirement" >&5
-echo "${ECHO_T}$pupa_cv_i386_asm_prefix_requirement" >&6
+echo "$as_me:$LINENO: result: $grub_cv_i386_asm_prefix_requirement" >&5
+echo "${ECHO_T}$grub_cv_i386_asm_prefix_requirement" >&6
 
 
 echo "$as_me:$LINENO: checking for .code16 addr32 assembler support" >&5
 echo $ECHO_N "checking for .code16 addr32 assembler support... $ECHO_C" >&6
-if test "${pupa_cv_i386_asm_addr32+set}" = set; then
+if test "${grub_cv_i386_asm_addr32+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat > conftest.s.in <<\EOF
@@ -3196,7 +3196,7 @@ else
 l1:	@ADDR32@	movb	%al, l1
 EOF
 
-if test "x$pupa_cv_i386_asm_prefix_requirement" = xyes; then
+if test "x$grub_cv_i386_asm_prefix_requirement" = xyes; then
   sed -e s/@ADDR32@/addr32/ < conftest.s.in > conftest.s
 else
   sed -e s/@ADDR32@/addr32\;/ < conftest.s.in > conftest.s
@@ -3208,21 +3208,21 @@ if { ac_try='${CC-cc} ${CFLAGS} -c conftest.s'
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; } && test -s conftest.o; then
-  pupa_cv_i386_asm_addr32=yes
+  grub_cv_i386_asm_addr32=yes
 else
-  pupa_cv_i386_asm_addr32=no
+  grub_cv_i386_asm_addr32=no
 fi
 
 rm -f conftest*
 fi
 
 
-echo "$as_me:$LINENO: result: $pupa_cv_i386_asm_addr32" >&5
-echo "${ECHO_T}$pupa_cv_i386_asm_addr32" >&6
+echo "$as_me:$LINENO: result: $grub_cv_i386_asm_addr32" >&5
+echo "${ECHO_T}$grub_cv_i386_asm_addr32" >&6
 
 echo "$as_me:$LINENO: checking whether an absolute indirect call/jump must not be prefixed with an asterisk" >&5
 echo $ECHO_N "checking whether an absolute indirect call/jump must not be prefixed with an asterisk... $ECHO_C" >&6
-if test "${pupa_cv_i386_asm_absolute_without_asterisk+set}" = set; then
+if test "${grub_cv_i386_asm_absolute_without_asterisk+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat > conftest.s <<\EOF
@@ -3238,16 +3238,16 @@ if { ac_try='${CC-cc} ${CFLAGS} -c conftest.s'
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; } && test -s conftest.o; then
-  pupa_cv_i386_asm_absolute_without_asterisk=no
+  grub_cv_i386_asm_absolute_without_asterisk=no
 else
-  pupa_cv_i386_asm_absolute_without_asterisk=yes
+  grub_cv_i386_asm_absolute_without_asterisk=yes
 fi
 
 rm -f conftest*
 fi
 
 
-if test "x$pupa_cv_i386_asm_absolute_without_asterisk" = xyes; then
+if test "x$grub_cv_i386_asm_absolute_without_asterisk" = xyes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define ABSOLUTE_WITHOUT_ASTERISK 1
@@ -3255,12 +3255,12 @@ _ACEOF
 
 fi
 
-echo "$as_me:$LINENO: result: $pupa_cv_i386_asm_absolute_without_asterisk" >&5
-echo "${ECHO_T}$pupa_cv_i386_asm_absolute_without_asterisk" >&6
+echo "$as_me:$LINENO: result: $grub_cv_i386_asm_absolute_without_asterisk" >&5
+echo "${ECHO_T}$grub_cv_i386_asm_absolute_without_asterisk" >&6
 
 echo "$as_me:$LINENO: checking if GCC has the regparm=3 bug" >&5
 echo $ECHO_N "checking if GCC has the regparm=3 bug... $ECHO_C" >&6
-if test "${pupa_cv_i386_check_nested_functions+set}" = set; then
+if test "${grub_cv_i386_check_nested_functions+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   if test "$cross_compiling" = yes; then
@@ -3305,24 +3305,24 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  pupa_cv_i386_check_nested_functions=yes
+  grub_cv_i386_check_nested_functions=yes
 else
   echo "$as_me: program exited with status $ac_status" >&5
 echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 ( exit $ac_status )
-pupa_cv_i386_check_nested_functions=no
+grub_cv_i386_check_nested_functions=no
 fi
 rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 
 
-echo "$as_me:$LINENO: result: $pupa_cv_i386_check_nested_functions" >&5
-echo "${ECHO_T}$pupa_cv_i386_check_nested_functions" >&6
+echo "$as_me:$LINENO: result: $grub_cv_i386_check_nested_functions" >&5
+echo "${ECHO_T}$grub_cv_i386_check_nested_functions" >&6
 
-if test "x$pupa_cv_i386_check_nested_functions" = xyes; then
+if test "x$grub_cv_i386_check_nested_functions" = xyes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define NESTED_FUNC_ATTR __attribute__ ((__regparm__ (2)))
@@ -3531,7 +3531,7 @@ fi
 
 echo "$as_me:$LINENO: checking whether ${OBJCOPY} works for absolute addresses" >&5
 echo $ECHO_N "checking whether ${OBJCOPY} works for absolute addresses... $ECHO_C" >&6
-if test "${pupa_cv_prog_objcopy_absolute+set}" = set; then
+if test "${grub_cv_prog_objcopy_absolute+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat > conftest.c <<\EOF
@@ -3552,7 +3552,7 @@ else
 echo "$as_me: error: ${CC-cc} cannot compile C source code" >&2;}
    { (exit 1); exit 1; }; }
 fi
-pupa_cv_prog_objcopy_absolute=yes
+grub_cv_prog_objcopy_absolute=yes
 for link_addr in 2000 8000 7C00; do
   if { ac_try='${CC-cc} ${CFLAGS} -nostdlib -Wl,-N -Wl,-Ttext -Wl,$link_addr conftest.o -o conftest.exec'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
@@ -3584,19 +3584,19 @@ echo "$as_me: error: ${OBJCOPY-objcopy} cannot create binary files" >&2;}
   (exit $ac_status); }; }; then
     mv -f conftest conftest.old
   else
-    pupa_cv_prog_objcopy_absolute=no
+    grub_cv_prog_objcopy_absolute=no
     break
   fi
 done
 rm -f conftest*
 fi
 
-echo "$as_me:$LINENO: result: $pupa_cv_prog_objcopy_absolute" >&5
-echo "${ECHO_T}$pupa_cv_prog_objcopy_absolute" >&6
+echo "$as_me:$LINENO: result: $grub_cv_prog_objcopy_absolute" >&5
+echo "${ECHO_T}$grub_cv_prog_objcopy_absolute" >&6
 
-if test "x$pupa_cv_prog_objcopy_absolute" = xno; then
-  { { echo "$as_me:$LINENO: error: PUPA requires a working absolute objcopy; upgrade your binutils" >&5
-echo "$as_me: error: PUPA requires a working absolute objcopy; upgrade your binutils" >&2;}
+if test "x$grub_cv_prog_objcopy_absolute" = xno; then
+  { { echo "$as_me:$LINENO: error: GRUB requires a working absolute objcopy; upgrade your binutils" >&5
+echo "$as_me: error: GRUB requires a working absolute objcopy; upgrade your binutils" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -5495,7 +5495,7 @@ CFLAGS="$tmp_CFLAGS"
 CPPFLAGS="$tmp_CPPFLAGS"
 
 # Output files.
-                    ac_config_links="$ac_config_links include/pupa/cpu:include/pupa/$host_cpu include/pupa/machine:include/pupa/$host_cpu/$host_vendor"
+                    ac_config_links="$ac_config_links include/grub/cpu:include/grub/$host_cpu include/grub/machine:include/grub/$host_cpu/$host_vendor"
 
           ac_config_files="$ac_config_files Makefile"
 
@@ -6030,8 +6030,8 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "stamp-h" ) CONFIG_FILES="$CONFIG_FILES stamp-h" ;;
-  "include/pupa/cpu" ) CONFIG_LINKS="$CONFIG_LINKS include/pupa/cpu:include/pupa/$host_cpu" ;;
-  "include/pupa/machine" ) CONFIG_LINKS="$CONFIG_LINKS include/pupa/machine:include/pupa/$host_cpu/$host_vendor" ;;
+  "include/grub/cpu" ) CONFIG_LINKS="$CONFIG_LINKS include/grub/cpu:include/grub/$host_cpu" ;;
+  "include/grub/machine" ) CONFIG_LINKS="$CONFIG_LINKS include/grub/machine:include/grub/$host_cpu/$host_vendor" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
