fix the memcheck problem in the grub shell.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1625,9 +1625,143 @@ EOF
 
 fi
 
+
+echo $ac_n "checking if start is defined by the compiler""... $ac_c" 1>&6
+echo "configure:1631: checking if start is defined by the compiler" >&5
+if eval "test \"\${grub_cv_check_start_symbol+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.c <<\EOF
+int
+main (void)
+{
+  asm ("incl start");
+  return 0;
+}
+EOF
+
+if { ac_try='${CC-cc} conftest.c -o conftest'; { (eval echo configure:1644: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } && test -s conftest; then
+  grub_cv_check_start_symbol=yes
+  cat >> confdefs.h <<\EOF
+#define HAVE_START_SYMBOL 1
+EOF
+
+else
+  grub_cv_check_start_symbol=no
+fi
+
+rm -f conftest*
+fi
+
+
+echo "$ac_t""$grub_cv_check_start_symbol" 1>&6
+
+
+echo $ac_n "checking if _start is defined by the compiler""... $ac_c" 1>&6
+echo "configure:1662: checking if _start is defined by the compiler" >&5
+if eval "test \"\${grub_cv_check_uscore_start_symbol+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.c <<\EOF
+int
+main (void)
+{
+  asm ("incl _start");
+  return 0;
+}
+EOF
+
+if { ac_try='${CC-cc} conftest.c -o conftest'; { (eval echo configure:1675: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } && test -s conftest; then
+  grub_cv_check_uscore_start_symbol=yes
+  cat >> confdefs.h <<\EOF
+#define HAVE_USCORE_START_SYMBOL 1
+EOF
+
+else
+  grub_cv_check_uscore_start_symbol=no
+fi
+
+rm -f conftest*
+fi
+
+
+echo "$ac_t""$grub_cv_check_uscore_start_symbol" 1>&6
+
+if test "x$grub_cv_check_start_symbol" != "xyes" \
+	-a "x$grub_cv_check_uscore_start_symbol" != "xyes"; then
+  { echo "configure: error: Neither start nor _start is defined" 1>&2; exit 1; }
+fi
+
+
+echo $ac_n "checking if end is defined by the compiler""... $ac_c" 1>&6
+echo "configure:1698: checking if end is defined by the compiler" >&5
+if eval "test \"\${grub_cv_check_end_symbol+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.c <<\EOF
+int
+main (void)
+{
+  asm ("incl end);
+  return 0;
+}
+EOF
+
+if { ac_try='${CC-cc} conftest.c -o conftest'; { (eval echo configure:1711: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } && test -s conftest; then
+  grub_cv_check_end_symbol=yes
+  cat >> confdefs.h <<\EOF
+#define HAVE_END_SYMBOL 1
+EOF
+
+else
+  grub_cv_check_end_symbol=no
+fi
+
+rm -f conftest*
+fi
+
+
+echo "$ac_t""$grub_cv_check_end_symbol" 1>&6
+
+
+echo $ac_n "checking if _end is defined by the compiler""... $ac_c" 1>&6
+echo "configure:1729: checking if _end is defined by the compiler" >&5
+if eval "test \"\${grub_cv_check_uscore_end_symbol+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.c <<\EOF
+int
+main (void)
+{
+  asm ("incl _end");
+  return 0;
+}
+EOF
+
+if { ac_try='${CC-cc} conftest.c -o conftest'; { (eval echo configure:1742: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } && test -s conftest; then
+  grub_cv_check_uscore_end_symbol=yes
+  cat >> confdefs.h <<\EOF
+#define HAVE_USCORE_END_SYMBOL 1
+EOF
+
+else
+  grub_cv_check_uscore_end_symbol=no
+fi
+
+rm -f conftest*
+fi
+
+
+echo "$ac_t""$grub_cv_check_uscore_end_symbol" 1>&6
+
+if test "x$grub_cv_check_end_symbol" != "xyes" \
+	-a "x$grub_cv_check_uscore_end_symbol" != "xyes"; then
+  { echo "configure: error: Neither end nor _end is defined" 1>&2; exit 1; }
+fi
+
 # Check for curses libraries.
 echo $ac_n "checking for wgetch in -lncurses""... $ac_c" 1>&6
-echo "configure:1631: checking for wgetch in -lncurses" >&5
+echo "configure:1765: checking for wgetch in -lncurses" >&5
 ac_lib_var=`echo ncurses'_'wgetch | sed 'y%./+-:%__p__%'`
 if eval "test \"\${ac_cv_lib_$ac_lib_var+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1635,7 +1769,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lncurses  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1639 "configure"
+#line 1773 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1646,7 +1780,7 @@ int main() {
 wgetch()
 ; return 0; }
 EOF
-if { (eval echo configure:1650: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1784: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1669,7 +1803,7 @@ EOF
 else
   echo "$ac_t""no" 1>&6
 echo $ac_n "checking for wgetch in -lcurses""... $ac_c" 1>&6
-echo "configure:1673: checking for wgetch in -lcurses" >&5
+echo "configure:1807: checking for wgetch in -lcurses" >&5
 ac_lib_var=`echo curses'_'wgetch | sed 'y%./+-:%__p__%'`
 if eval "test \"\${ac_cv_lib_$ac_lib_var+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1677,7 +1811,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lcurses  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1681 "configure"
+#line 1815 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1688,7 +1822,7 @@ int main() {
 wgetch()
 ; return 0; }
 EOF
-if { (eval echo configure:1692: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1826: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1718,7 +1852,7 @@ fi
 
 # Check for headers.
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:1722: checking how to run the C preprocessor" >&5
+echo "configure:1856: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -1733,13 +1867,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 1737 "configure"
+#line 1871 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1743: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1877: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -1750,13 +1884,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 1754 "configure"
+#line 1888 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1760: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1894: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -1767,13 +1901,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -nologo -E"
   cat > conftest.$ac_ext <<EOF
-#line 1771 "configure"
+#line 1905 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1777: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1911: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -1801,17 +1935,17 @@ for ac_hdr in string.h strings.h ncurses/curses.h ncurses.h curses.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:1805: checking for $ac_hdr" >&5
+echo "configure:1939: checking for $ac_hdr" >&5
 if eval "test \"\${ac_cv_header_$ac_safe+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1810 "configure"
+#line 1944 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1815: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1949: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
